# Generated by Django 4.2.7 on 2023-11-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagee',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
