# Generated by Django 4.2.7 on 2023-11-21 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_imagee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imagee',
            new_name='image',
        ),
    ]
